docker/ofa: move PARAMDIR from ~/.jsk_vil_apis to ~/.ros/data/jsk_per…
mqcmd196/jsk_recognition pull request #4
Opened 2023-04-04 01:48 UTC by k-okada

…ception/vil_params as other jsk_perception tools

2023-04-04 09:41 UTC, k-okada commented
@mqcmd196 added clip classification task

2023-04-05 01:41 UTC, mqcmd196 requested changes
Thank you for your feature. I added some comment about variable, config name

2023-04-05 01:41 UTC, mqcmd196 commented on jsk_perception/cfg/Classification.cfg
> +PACKAGE = "jsk_vil_msgs"
PACKAGE name should be "jsk_perception" ?

2023-04-05 01:41 UTC, mqcmd196 commented on jsk_perception/node_scripts/classification_client_node.py
> +        self.clip_result_pub = rospy.Publisher("~clip_result", ClassificationResult, queue_size=1)
It seems those topic name should be `classification_result` or something...?

2023-04-11 02:19 UTC, merged